// FontAwesome configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import { config } from '@fortawesome/fontawesome-svg-core';

// Import specific icons you want to use
import { 
  faHeart,
  faUser,
  faHome,
  faEnvelope,
  faPhone,
  faStar,
  faCheck,
  faArrowRight,
  faDownload,
  faCode,
  faTrophy,
  faClock,
  faUsers,
  faCalendar,
  faMapMarkerAlt,
  faGraduationCap,
  faLaptopCode,
  faRocket,
  faBolt,
  faAward,
  faGift,
  faHandshake,
  faLightbulb,
  faBullseye,
  faMedal,
  faChartLine,
  faGlobe,
  faMobile,
  faDesktop,
  faDatabase,
  faCloud,
  faShield,
  faCog,
  faSearch,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faUpload,
  faShare,
  faLink,
  faExternalLinkAlt
} from '@fortawesome/free-solid-svg-icons';

import {
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faInstagram,
  faYoutube,
  faDiscord,
  faSlack,
  faWhatsapp,
  faTelegram,
  faReact,
  faNodeJs,
  faPython,
  faJsSquare,
  faHtml5,
  faCss3Alt,
  faBootstrap,
  faGitAlt,
  faDocker,
  faAws,
  faGoogle
} from '@fortawesome/free-brands-svg-icons';

import {
  faHeart as faHeartRegular,
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faStar as faStarRegular,
  faCalendar as faCalendarRegular,
  faComment as faCommentRegular,
  faFile as faFileRegular,
  faFolder as faFolderRegular,
  faImage as faImageRegular,
  faPlayCircle as faPlayCircleRegular
} from '@fortawesome/free-regular-svg-icons';

// Tell Font Awesome to skip adding the CSS automatically 
// since we're using a bundler
config.autoAddCss = false;

// Add icons to the library so you can use them by name
library.add(
  // Solid icons
  faHeart,
  faUser,
  faHome,
  faEnvelope,
  faPhone,
  faStar,
  faCheck,
  faArrowRight,
  faDownload,
  faCode,
  faTrophy,
  faClock,
  faUsers,
  faCalendar,
  faMapMarkerAlt,
  faGraduationCap,
  faLaptopCode,
  faRocket,
  faBolt,
  faAward,
  faGift,
  faHandshake,
  faLightbulb,
  faBullseye,
  faMedal,
  faChartLine,
  faGlobe,
  faMobile,
  faDesktop,
  faDatabase,
  faCloud,
  faShield,
  faCog,
  faSearch,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faUpload,
  faShare,
  faLink,
  faExternalLinkAlt,
  
  // Brand icons
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faInstagram,
  faYoutube,
  faDiscord,
  faSlack,
  faWhatsapp,
  faTelegram,
  faReact,
  faNodeJs,
  faPython,
  faJsSquare,
  faHtml5,
  faCss3Alt,
  faBootstrap,
  faGitAlt,
  faDocker,
  faAws,
  faGoogle,
  
  // Regular icons
  faHeartRegular,
  faUserRegular,
  faEnvelopeRegular,
  faStarRegular,
  faCalendarRegular,
  faCommentRegular,
  faFileRegular,
  faFolderRegular,
  faImageRegular,
  faPlayCircleRegular
);
